### ISSUE TITLE
Write the abstract

### ISSUE THREAD

**Issue by morgaalb** [100k-rocketry/groundstation#1]
Project abstract, with a concise introduction to the problem you are trying to solve and your proposed solution.

**Comment by anisimon** [comment]
I feel like this is done, should we go ahead and close it? Or is there something else someone wanted to add?

**Comment by morgaalb** [comment]
I think we should take a second look at it after we write the whole thing (usually you write abstracts last) and we also need to incorporate some of the feedback that we received when we brought it to class.
