### ISSUE TITLE
Write the proposed solution

### ISSUE THREAD

**Issue by morgaalb** [100k-rocketry/groundstation#3]
Proposed solution: What is your solution going to be able to do? How does this meet the needs of the problem? What do you think you will show at Expo? Exact details not necessary, but you should have a high level view of what will be presented.

**Comment by morgaalb** [comment]
I dumped some stuff from the definition into this section. It still needs a LOT of formatting.

**Comment by anisimon** [comment]
I'll go ahead and pick up it up.
